import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.scss";
import { Toaster, toast } from "sonner";
import emailjs from "@emailjs/browser";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const sendEmail = (e) => {
    e.preventDefault();
    emailjs
      .sendForm(
        "service_q0rmot4",
        "template_kfvcjr2",
        e.target,
        "giaNptOM4AJJx8eGb"
      )
      .then(() => toast.success("Mensaje Enviado"))
      .catch((err) => toast.error("Mensaje no Enviado"));

    e.target.formNombre.value = "";
    e.target.formTitulo.value = "";
    e.target.formLink.value = "";
  };

  return (
    <>
      <Head>
        <title>Saabtian | Videos para YouTube</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <section className={styles.header}>
          <div className={styles.video}>
            <iframe
              className={styles.videoYT}
              width="600"
              height="315"
              src="https://www.youtube.com/embed/f5H6eBFdb9k?si=53tVULjJdiJZxiyy"
              title="YouTube video player"
              frameborder="0"
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
              allowfullscreen
            ></iframe>

            <a href="https://streamable.com/" target={"_blank"}>
              <p>Ir a streamable</p>
            </a>
          </div>
        </section>

        <section className={styles.form}>
          <form action="" className="form" onSubmit={sendEmail}>
            <p className="form__p">Nombre de Familia:</p>
            <input
              type="text"
              name="from_name"
              id="formNombre"
              className="form__input"
              placeholder="Nombre"
              required
            />
            <p className="form__p">Titulo del clip:</p>
            <input
              type="text"
              name="titulo"
              id="formTitulo"
              className="form__input"
              placeholder="Titulo de la idea"
              required
              minLength={6}
            />
            <p className="form__p">Link al video:</p>
            <input
              name="message"
              id="formLink"
              className="form__area"
              placeholder="Descripcion"
              required
            />
            <button type="submit" className="form__submit">
              Enviar
            </button>
          </form>
        </section>

        <Toaster />
      </main>
    </>
  );
}
